name: Manual
on:
  workflow_dispatch:  # 手動実行イベント
    inputs:
      greeting:  # 入力パラメーター名
        type: string  #データ型
        default: "Hello, world!"  #入力パラメーターのデフォルト値
        required: true  #入力パラメーターの必須フラグ
        description: A cheerful world  #入力パラメーターの概要
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}" # 入力パラメーター「greething」の値を参照
